/* PARA PODER AGRUPAR EL MONTO DE LAS VENTAS POR GRUPO  */



CREATE TABLE  PUNTOVENTA_GRUPO (
  ID_GRUPO INT(5) NOT NULL AUTO_INCREMENT,
  NOMBRE_GRUPO VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_GRUPO))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;



ALTER TABLE 
PUNTOVENTA_CATEGORIA 
ADD ID_GRUPO INT(5);


ALTER TABLE 
PUNTOVENTA_CATEGORIA 
ADD CONSTRAINT FK_GRUPO FOREIGN KEY (ID_GRUPO) 
REFERENCES PUNTOVENTA_GRUPO(ID_GRUPO)
ON DELETE CASCADE
;
