/*  NUEVA FUNCIONALIDAD: CORTES DE CAJA */


ALTER TABLE 
PUNTOVENTA_GRUPO
ADD ID_EMPRESA INT(5);

ALTER TABLE 
PUNTOVENTA_GRUPO 
ADD CONSTRAINT FK_GRUPO_EMPRESA FOREIGN KEY (ID_EMPRESA) 
REFERENCES PUNTOVENTA_EMPRESA(ID_EMPRESA)
ON DELETE CASCADE
;
