-- MySQL Script generated by MySQL Workbench
-- 05/08/18 21:39:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table `puntoventa_producto`
-- -----------------------------------------------------

ALTER TABLE puntoventa_producto 
ADD `ID_EMPRESA` INT NULL, 
ADD CONSTRAINT `FK_EMPRESA_PRODUCTO` 
	FOREIGN KEY (`ID_EMPRESA`) 
	REFERENCES `puntoventa_empresa` (`ID_EMPRESA`) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE; 

CREATE INDEX `FK_EMPRESA_IDX` ON `puntoventa_producto` (`ID_EMPRESA` ASC);


-- -----------------------------------------------------
-- Table `puntoventa_corte_caja`
-- -----------------------------------------------------
ALTER TABLE `puntoventa_corte_caja` 
ADD `ID_EMPRESA` INT NULL, 
ADD CONSTRAINT `FK_EMPRESA_CORTE` 
	FOREIGN KEY (`ID_EMPRESA`) 
	REFERENCES `puntoventa_empresa` (`ID_EMPRESA`) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE; 

CREATE INDEX `FK_EMPRESA_IDX` ON `puntoventa_corte_caja` (`ID_EMPRESA` ASC);


-- -----------------------------------------------------
-- Table `puntoventa_venta`
-- -----------------------------------------------------
ALTER TABLE  `puntoventa_venta` 
ADD `ID_EMPRESA` INT NULL, 
ADD CONSTRAINT `FK_EMPRESA_VENTA` 
	FOREIGN KEY (`ID_EMPRESA`) 
	REFERENCES `puntoventa_empresa` (`ID_EMPRESA`) 
	ON DELETE CASCADE 
	ON UPDATE CASCADE; 

CREATE INDEX `FK_EMPRESA_IDX` ON `puntoventa_venta` (`ID_EMPRESA` ASC);


-- -----------------------------------------------------
-- Table `puntoventa_usuario`
-- -----------------------------------------------------
ALTER TABLE  `puntoventa_usuario`
ADD `USERNAME_DESK` VARCHAR(45) NULL,
ADD `PASSWORD_DESK` VARCHAR(45) NULL;

CREATE UNIQUE INDEX `USERNAME_DESK_UNIQUE` ON `puntoventa_usuario` (`USERNAME_DESK` ASC);