-- MySQL Script generated by sazpeitia
-- 05/12/18 09:58:00
-- Version: 1.54
-- Se incrementa la longitud del campo direccion

-- ----------------------------------------------------- 
-- Table puntoventa_empresa
-- ----------------------------------------------------- 
 
ALTER TABLE puntoventa_empresa 
MODIFY COLUMN DIRECCION VARCHAR(150); 
