-- MySQL Script generated by MySQL Workbench
-- 09/13/19 06:17:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Se adiciona por que JPA es requerido por lo menos una columna para insetar un nuevo valor

-- -----------------------------------------------------
-- Table `puntoventa_v16`.`PUNTOVENTA_COMMON_OBJECT`
-- -----------------------------------------------------
ALTER TABLE  PUNTOVENTA_COMMON_OBJECT 
  ADD FECHA_CREACION DATETIME NULL DEFAULT NULL
  
  ;

