/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa.frames;

import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import puntodeventa.PuntoVentaPrinter;
import puntodeventa.PuntoventaCorteCaja;
import puntodeventa.sql.PuntoventaVenta;

/**
 *
 * @author SERVIDOR-PC
 */
public class JDialogReporteVentas extends javax.swing.JDialog {

    /**
     * Creates new form ReporteVentasJDialog
     */
    public JDialogReporteVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cerrarVentanaJButton = new javax.swing.JButton();
        hacerCorteJButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteVentasJTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REPORTE DE VENTAS");

        cerrarVentanaJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cerrarVentanaJButton.setText("Cerrar ventana");
        cerrarVentanaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarVentanaJButtonActionPerformed(evt);
            }
        });

        hacerCorteJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hacerCorteJButton.setText("Hacer corte");
        hacerCorteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hacerCorteJButtonActionPerformed(evt);
            }
        });

        jPanel1.setAutoscrolls(true);

        reporteVentasJTextPane.setEditable(false);
        reporteVentasJTextPane.setContentType("text/html"); // NOI18N
        reporteVentasJTextPane.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(reporteVentasJTextPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 434, Short.MAX_VALUE)
                        .addComponent(hacerCorteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cerrarVentanaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cerrarVentanaJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(hacerCorteJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened


    }//GEN-LAST:event_formWindowOpened

    private void cerrarVentanaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarVentanaJButtonActionPerformed

        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cerrarVentanaJButtonActionPerformed

    private void hacerCorteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hacerCorteJButtonActionPerformed

        if (listaVenta.size() > 0) {
            int resultado = JOptionPane.showConfirmDialog(this, "Se realizará el "
                    + "corte de caja de todas las ventas ¿Desea continuar?");
            if (resultado == JOptionPane.YES_OPTION) {

                em.getTransaction().begin();

                Date fechaCorte = new Date();
                PuntoventaCorteCaja corteCaja = new PuntoventaCorteCaja();
                corteCaja.setFechaCorte(fechaCorte);
                double sumaTotal = 0.0;

                for (PuntoventaVenta venta : listaVenta) {

                    sumaTotal += venta.getTotalVenta();
                    venta.setIdCorteCaja(corteCaja);
                }
                corteCaja.setTotalRecaudado(sumaTotal);

                em.persist(corteCaja);
                em.getTransaction().commit();

                

                String formatoMensaje = String.format("Se ha realizado el corte "
                        + "correctamente. Favor de retirar $%.2f de la caja", sumaTotal);
                JOptionPane.showMessageDialog(this, formatoMensaje);
                
                int resultado2 = JOptionPane.showConfirmDialog(this, "¿Desea guardar el corte de caja en un archivo html? ");
                
                if ( resultado2 == JOptionPane.YES_OPTION ) {
                    
                    PuntoVentaPrinter impresora = new PuntoVentaPrinter();
                    Date currentDate = Calendar.getInstance(Locale.getDefault()).getTime();
                    SimpleDateFormat formato = new SimpleDateFormat("yyyMMdd-hhmmss");
                    String fechaFile = formato.format(currentDate);
                    String file = "ReporteVentas" + fechaFile + ".html";
                    impresora.printHtmlToFile(reporteVentasJTextPane.getText(),file);
                    
                    JOptionPane.showMessageDialog(this, "Se ha guardado el archivo html exitosamente. Busque en la carpeta donde esta instalado el punto de venta.");
                }
                
                obtenerVentasDelDia();
                mostrarListaVentaHtml();
            }
        } else {

            JOptionPane.showMessageDialog(this, "No existen ventas para realizar el corte. Favor de verificar.");
        }
    }//GEN-LAST:event_hacerCorteJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogReporteVentas dialog = new JDialogReporteVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // custom methods
    public void customInit() {

        obtenerVentasDelDia();
        mostrarListaVentaHtml();
    }

    private void obtenerVentasDelDia() {

        TypedQuery<PuntoventaVenta> typedQuery;
        typedQuery = em.createNamedQuery("PuntoventaVenta.findByIdCorteCajaNull", PuntoventaVenta.class);

        // Date timeStamp = Calendar.getInstance().getTime();
        listaVenta = typedQuery.getResultList();
    }

    private void mostrarListaVentaHtml() {

        reporteVentasJTextPane.setText("");

        String htmlTextBegin = "<html><body>";
        String htmlBodyTableHeader = "<table border=\"3\" style=\"width:100%\"><tr>"
                + "<td>Número de venta</td><td>Fecha</td><td>Total</td>"
                + "<td>Pago cliente</td><td>Cambio cliente</td></tr>";
        String htmlBodyTableContent = "";
        String htmlTextEnd = "</body></html>";

        int row = 1;

        for (PuntoventaVenta venta : listaVenta) {

            String fechaFormat = "";
            String totalCompraFormat = String.format("$%.2f", venta.getTotalVenta());
            String pagoClienteFormat = String.format("$%.2f", venta.getPagoVenta());
            String cambioClienteFormat = String.format("$%.2f", venta.getCambioVenta());
            DateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            fechaFormat = formato.format(venta.getFechaVenta());
            htmlBodyTableContent += "<tr><td>Venta " + row + "</td>";
            htmlBodyTableContent += "<td>" + fechaFormat + "</td>";
            htmlBodyTableContent += "<td>" + totalCompraFormat + "</td>";
            htmlBodyTableContent += "<td>" + pagoClienteFormat + "</td>";
            htmlBodyTableContent += "<td>" + cambioClienteFormat + "</td></tr>";

            row++;
        }

        htmlBodyTableContent += "</table>";
        reporteVentasJTextPane.setText(htmlTextBegin + htmlBodyTableHeader + htmlBodyTableContent + htmlTextEnd);
    }

    // custom variables
    private EntityManagerFactory emf;
    private EntityManager em;

    private List<PuntoventaVenta> listaVenta;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarVentanaJButton;
    private javax.swing.JButton hacerCorteJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane reporteVentasJTextPane;
    // End of variables declaration//GEN-END:variables

    /**
     * @param emf the emf to set
     */
    public void setEmf(EntityManagerFactory emf) {
        this.emf = emf;
    }

    /**
     * @param em the em to set
     */
    public void setEm(EntityManager em) {
        this.em = em;
    }
}
