/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa.frames;

import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;
import javax.swing.table.DefaultTableModel;
import puntodeventa.sql.PuntoventaCarrito;
import puntodeventa.sql.PuntoventaCarrito_;
import puntodeventa.sql.PuntoventaVenta;

/**
 *
 * @author asus
 */
public class JDialogDetalleVenta extends javax.swing.JDialog {

    /**
     * Creates new form JDialogDetalleVenta
     */
    public JDialogDetalleVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrarVentana = new javax.swing.JButton();
        jLabel1Folio = new javax.swing.JLabel();
        jLabel2Fecha = new javax.swing.JLabel();
        jLabel3Total = new javax.swing.JLabel();
        jLabel4Pago = new javax.swing.JLabel();
        jLabel5Cambio = new javax.swing.JLabel();
        jLabel6Lista = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Items = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonCerrarVentana.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonCerrarVentana.setText("Cerrar");
        jButtonCerrarVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarVentanaActionPerformed(evt);
            }
        });

        jLabel1Folio.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1Folio.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel1Folio.setText("Folio de venta: ");
        jLabel1Folio.setOpaque(true);

        jLabel2Fecha.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2Fecha.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2Fecha.setText("Fecha de venta:");
        jLabel2Fecha.setOpaque(true);

        jLabel3Total.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3Total.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel3Total.setText("Total:");
        jLabel3Total.setOpaque(true);

        jLabel4Pago.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4Pago.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel4Pago.setText("Pago:");
        jLabel4Pago.setOpaque(true);

        jLabel5Cambio.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5Cambio.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel5Cambio.setText("Cambio:");
        jLabel5Cambio.setOpaque(true);

        jLabel6Lista.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel6Lista.setText("Lista de productos vendidos");

        jTable1Items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CANTIDAD", "PRODUCTO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1Items);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6Lista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3Total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1Folio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4Pago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5Cambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1Folio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6Lista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3Total, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5Cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCerrarVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarVentanaActionPerformed
        
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButtonCerrarVentanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogDetalleVenta dialog = new JDialogDetalleVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarVentana;
    private javax.swing.JLabel jLabel1Folio;
    private javax.swing.JLabel jLabel2Fecha;
    private javax.swing.JLabel jLabel3Total;
    private javax.swing.JLabel jLabel4Pago;
    private javax.swing.JLabel jLabel5Cambio;
    private javax.swing.JLabel jLabel6Lista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Items;
    // End of variables declaration//GEN-END:variables

    private EntityManager em;
    private PuntoventaVenta venta;
    
    void setEm(EntityManager em) {
        
        this.em = em;
    }

    void setVenta(PuntoventaVenta ventaSeleccionado) {
        
        this.venta = ventaSeleccionado;
    }
    
    private List<PuntoventaCarrito> sqlCarritoVenta( PuntoventaVenta venta ){
     
        CriteriaBuilder cb = em.getCriteriaBuilder();
            
        CriteriaQuery<PuntoventaCarrito> cq = cb.createQuery(PuntoventaCarrito.class);
        Root<PuntoventaCarrito> detalleVenta = cq.from(PuntoventaCarrito.class);
  
        cq.where(cb.equal(detalleVenta.get(PuntoventaCarrito_.idVenta),venta));
        cq.select(detalleVenta);

        TypedQuery<PuntoventaCarrito> q = em.createQuery(cq);
        List<PuntoventaCarrito> listaItems = q.getResultList();
        return listaItems;
    }    
    
    private void adicionarFilaItemsJTable(PuntoventaCarrito item) {

        DefaultTableModel modelo = (DefaultTableModel) jTable1Items.getModel();
        modelo.addRow(new Object[]{
            item.getCantidadProducto(),
            item.getIdProducto().getNombreProducto(),
            item.getTotal()
        });
    }
    
    private void eliminarFilasItemsJTable() {

        DefaultTableModel dm = (DefaultTableModel) jTable1Items.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }
    
    private void mostrarItemsEnTabla(){
        
        eliminarFilasItemsJTable();
        List<PuntoventaCarrito> items = sqlCarritoVenta(venta);
        for ( PuntoventaCarrito item :  items)
            adicionarFilaItemsJTable(item);
    }
    
    private void mostrarDetalleVenta(){
        
        String folioS = String.format(
                "%s %06d",jLabel1Folio.getText(),venta.getIdVenta());
        String fechaS = String.format(
                "%s %s",jLabel2Fecha.getText(),new SimpleDateFormat("dd/MM/yyyy, HH:mm:ss").format(venta.getFechaVenta()));
        String totalS = String.format(
                "%s $%.2f",jLabel3Total.getText(),venta.getTotalVenta());
        String pagoS = String.format(
                "%s $%.2f",jLabel4Pago.getText(),venta.getPagoVenta());
        String cambioS = String.format(
                "%s $%.2f",jLabel5Cambio.getText(),venta.getCambioVenta());
        
        jLabel1Folio.setText(folioS);
        jLabel2Fecha.setText(fechaS);
        jLabel3Total.setText(totalS);
        jLabel4Pago.setText(pagoS);
        jLabel5Cambio.setText(cambioS);
    }

    public void inicializar() {
        
        mostrarDetalleVenta();
        mostrarItemsEnTabla();
    }
}
