/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa.frames;

import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.TypedQuery;
import puntodeventa.sql.PuntoventaCarrito;
import puntodeventa.sql.PuntoventaVenta;

/**
 *
 * @author SERVIDOR-PC
 */
public class JDialogReporteGanancias extends javax.swing.JDialog {

    /**
     * Creates new form JDialogReporteGanancias
     */
    public JDialogReporteGanancias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteJTextPane = new javax.swing.JTextPane();
        cerrarVentanaJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tituloJLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tituloJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloJLabel.setText("GANANCIAS");

        reporteJTextPane.setEditable(false);
        reporteJTextPane.setContentType("text/html"); // NOI18N
        reporteJTextPane.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(reporteJTextPane);

        cerrarVentanaJButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cerrarVentanaJButton.setText("Cerrar ventana");
        cerrarVentanaJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarVentanaJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cerrarVentanaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cerrarVentanaJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarVentanaJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarVentanaJButtonActionPerformed

        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cerrarVentanaJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogReporteGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogReporteGanancias dialog = new JDialogReporteGanancias(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cerrarVentanaJButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane reporteJTextPane;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables

    private EntityManagerFactory emf;
    private EntityManager em;
    private List<PuntoventaVenta> listaObjectos;

    
    public void customInit() {

        obtenerObjetos();
        mostrarContenidoHTML();
    }
    
    private void obtenerObjetos() {
        
        TypedQuery<PuntoventaVenta> typedQuery;
        typedQuery = em.createNamedQuery("PuntoventaVenta.findAll", PuntoventaVenta.class);
        listaObjectos = typedQuery.getResultList();
    }

    private void mostrarContenidoHTML() {
        
        reporteJTextPane.setText("");
        
        String htmlTextBegin = "<html><body>";
        String htmlBodyTableHeader = "<table border=\"3\" style=\"width:100%\"><tr>"
                + "<td>Fecha de Venta</td><td>Total de Venta</td><td>Ganancia</td></tr>";
        String htmlBodyTableContent = "";
        String htmlTextEnd = "</body></html>";
        
        
        for ( PuntoventaVenta venta : listaObjectos ) {
            
            String totalVenta = String.format("$%.2f", venta.getTotalVenta() );
            DateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
            String fechaFormat = formato.format(venta.getFechaVenta());
            Double sumaGanancia = 0.0;
            
            
            List<PuntoventaCarrito> carrito = venta.getPuntoventaCarritoList();
            
            for ( PuntoventaCarrito item : carrito ) {
                
                Double totalPrecioVenta = item.getCantidadProducto() * item.getIdProducto().getPrecioVenta();
                
                Double totalPrecioCompra = item.getCantidadProducto() * item.getIdProducto().getPrecioCompra();
                sumaGanancia += (totalPrecioVenta - totalPrecioCompra);
            }
            
            String totalGanancia = String.format("$%.2f", sumaGanancia );
            
            htmlBodyTableContent += "<tr><td>" + fechaFormat + "</td>";
            htmlBodyTableContent += "<td>" + totalVenta + "</td>";
            htmlBodyTableContent += "<td>" + totalGanancia + "</td></tr>";
        }
        
        htmlBodyTableContent += "</table>";
        
        reporteJTextPane.setText(htmlTextBegin + htmlBodyTableHeader + htmlBodyTableContent + htmlTextEnd);
    }

    /**
     * @param emf the emf to set
     */
    public void setEmf(EntityManagerFactory emf) {
        this.emf = emf;
    }

    /**
     * @param em the em to set
     */
    public void setEm(EntityManager em) {
        this.em = em;
    }
}
