package puntoventa.frames;

import java.awt.event.WindowEvent;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import puntodeventa.sql.PuntoventaGrupo;

/**
 *
 * @author vladimirah
 */
public class JFrameGrupo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameCategoria
     */
    public JFrameGrupo() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gruposJTable = new javax.swing.JTable();
        nuevoGrupoButton = new javax.swing.JButton();
        editarGrupoButton = new javax.swing.JButton();
        eliminarjButton = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Subcategoria");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        closeButton.setText("Cerrar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMINISTRAR GRUPOS");

        gruposJTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        gruposJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "GRUPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gruposJTable.setRowHeight(40);
        gruposJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(gruposJTable);

        nuevoGrupoButton.setText("Nuevo");
        nuevoGrupoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoGrupoButtonActionPerformed(evt);
            }
        });

        editarGrupoButton.setText("Editar");
        editarGrupoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGrupoButtonActionPerformed(evt);
            }
        });

        eliminarjButton.setText("Eliminar");
        eliminarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nuevoGrupoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editarGrupoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eliminarjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nuevoGrupoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarGrupoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        inicializar();
    }//GEN-LAST:event_formWindowOpened

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed

        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeButtonActionPerformed

    private void nuevoGrupoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoGrupoButtonActionPerformed

        JDialogGrupo grupoDialogo = new JDialogGrupo(this, true);
        grupoDialogo.setEm(em);
        grupoDialogo.setModoEdicion(false);
        grupoDialogo.setLocationRelativeTo(this);
        grupoDialogo.setVisible(true);
        grupoDialogo.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        refrescarGrupos();
    }//GEN-LAST:event_nuevoGrupoButtonActionPerformed

    private void eliminarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarjButtonActionPerformed

        PuntoventaGrupo grupoSeleccionado = obtenerGrupoSeleccionado();

        String mensaje = "Va a eliminar un grupo. Si confirma, "
                + "las categorias del grupo no quedaran ligadas a algún grupo"
                + "\n¿Desea continuar?";
        String titulo = "¿Desea continuar?";

        if (grupoSeleccionado != null) {

            int respuesta = JOptionPane.showConfirmDialog(this, mensaje, titulo, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (respuesta == JOptionPane.YES_OPTION) {
                em.getTransaction().begin();
                em.remove(grupoSeleccionado);
                em.getTransaction().commit();
                refrescarGrupos();
            }
        }
    }//GEN-LAST:event_eliminarjButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        em.close();
        emf.close();
    }//GEN-LAST:event_formWindowClosing

    private void editarGrupoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGrupoButtonActionPerformed

        PuntoventaGrupo grupoSeleccionado = obtenerGrupoSeleccionado();
        if (grupoSeleccionado != null) {
            JDialogGrupo grupoDialogo = new JDialogGrupo(this, true);
            grupoDialogo.setEm(em);
            grupoDialogo.setModoEdicion(true);
            grupoDialogo.setGrupo(grupoSeleccionado);
            grupoDialogo.setLocationRelativeTo(this);
            grupoDialogo.setVisible(true);
            grupoDialogo.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
            refrescarGrupos();
        }
    }//GEN-LAST:event_editarGrupoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JFrameGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton editarGrupoButton;
    private javax.swing.JButton eliminarjButton;
    private javax.swing.JTable gruposJTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton nuevoGrupoButton;
    // End of variables declaration//GEN-END:variables

    // azptec: Custom code
    private EntityManagerFactory emf;
    private EntityManager em;

    private void inicializar() {

        inicarJPA();
        refrescarGrupos();
    }

    private void inicarJPA() {

        emf = Persistence.createEntityManagerFactory("PuntoDeVentaPU");
        em = emf.createEntityManager();
    }

    private void refrescarGrupos() {

        eliminarFilasGruposJTable();

        for (PuntoventaGrupo grupo : cargarGruposSQL()) {

            adicionarFilaGruposJTable(grupo);
        }
    }

    private List<PuntoventaGrupo> cargarGruposSQL() {

        List<PuntoventaGrupo> listaGrupos;
        TypedQuery<PuntoventaGrupo> typedQuery;
        typedQuery = em.createNamedQuery(
                "PuntoventaGrupo.findAll", PuntoventaGrupo.class);
        listaGrupos = typedQuery.getResultList();
        return listaGrupos;
    }

    private void eliminarFilasGruposJTable() {

        DefaultTableModel dm = (DefaultTableModel) gruposJTable.getModel();
        int rowCount = dm.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            dm.removeRow(i);
        }
    }

    private void adicionarFilaGruposJTable(PuntoventaGrupo grupo) {

        DefaultTableModel modelo = (DefaultTableModel) gruposJTable.getModel();
        modelo.addRow(new Object[]{
            grupo.getIdGrupo(),
            grupo
        });
    }

    private PuntoventaGrupo obtenerGrupoSeleccionado() {

        PuntoventaGrupo grupoSeleccionado = null;
        try {

            int idSelectedRow = gruposJTable.getSelectedRow();
            Object objectoSeleccionado = gruposJTable.getValueAt(idSelectedRow, 1);
            System.out.println(objectoSeleccionado);
            if (objectoSeleccionado instanceof PuntoventaGrupo) {
                grupoSeleccionado = (PuntoventaGrupo) objectoSeleccionado;
            }

        } catch (ArrayIndexOutOfBoundsException arrayIndexOutOfBoundsException) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un grupo de la lista");
        }
        return grupoSeleccionado;
    }
}
