/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntoventa.frames;

import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author sazpeitia
 */
public class JFrameCorteCaja extends javax.swing.JDialog {

    /**
     * @return the fechaCorte
     */
    public Date getFechaCorte() {
        return fechaCorte;
    }

    /**
     * @param fechaCorte the fechaCorte to set
     */
    public void setFechaCorte(Date fechaCorte) {
        this.fechaCorte = fechaCorte;
    }

    /**
     * @return the transaccionCancelada
     */
    public boolean isTransaccionCancelada() {
        return transaccionCancelada;
    }

    /**
     * @param transaccionCancelada the transaccionCancelada to set
     */
    public void setTransaccionCancelada(boolean transaccionCancelada) {
        this.transaccionCancelada = transaccionCancelada;
    }

    /**
     * @return the retiroCaja
     */
    public double getRetiroCaja() {
        return retiroCaja;
    }

    /**
     * @param retiroCaja the retiroCaja to set
     */
    public void setRetiroCaja(double retiroCaja) {
        
        this.retiroCaja = retiroCaja;
        this.jSpinnerRetiro.setValue(retiroCaja);
    }

    /**
     * @return the contado
     */
    public double getContado() {
        return contado;
    }

    /**
     * @param contado the contado to set
     */
    public void setContado(double contado) {
        this.contado = contado;
        this.jSpinnerContado.setValue(contado);
    }

    /**
     * @return the calculado
     */
    public double getCalculado() {
        return calculado;
    }

    /**
     * @param calculado the calculado to set
     */
    public void setCalculado(double calculado) {
        this.calculado = calculado;
        this.jTextFieldTotalVentas.setText(String.format("$%.2f",calculado));
    }

    /**
     * @return the diferencia
     */
    public double getDiferencia() {
        return diferencia;
    }

    /**
     * @param diferencia the diferencia to set
     */
    public void setDiferencia(double diferencia) {
        this.diferencia = diferencia;
        this.jTextFieldDiferencia.setText(String.format("$%.2f",diferencia));
    }

    /**
     * @return the totalCaja
     */
    public double getTotalCaja() {
        return totalCaja;
    }

    /**
     * @param totalCaja the totalCaja to set
     */
    public void setTotalCaja(double totalCaja) {
        this.totalCaja = totalCaja;
        this.jTextFieldTotalCaja.setText(String.format("$%.2f",totalCaja));
    }

    /**
     * Creates new form JFrameCorteCaja
     * @param parent
     * @param modal
     */
    public JFrameCorteCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldTotalVentas = new javax.swing.JTextField();
        jLabelTotalVentas = new javax.swing.JLabel();
        jLabelTotalReal = new javax.swing.JLabel();
        jLabelDiferencia = new javax.swing.JLabel();
        jTextFieldDiferencia = new javax.swing.JTextField();
        jLabelRetiro = new javax.swing.JLabel();
        jLabelTotalCaja = new javax.swing.JLabel();
        jTextFieldTotalCaja = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jSpinnerContado = new javax.swing.JSpinner();
        jSpinnerRetiro = new javax.swing.JSpinner();
        jSpinnerFechaCorte = new javax.swing.JSpinner();
        jLabelFechaCorte = new javax.swing.JLabel();
        jButtonCaluclarContado = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonAceptar.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jTextFieldTotalVentas.setEditable(false);
        jTextFieldTotalVentas.setBackground(new java.awt.Color(245, 150, 110));
        jTextFieldTotalVentas.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabelTotalVentas.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabelTotalVentas.setLabelFor(jTextFieldTotalVentas);
        jLabelTotalVentas.setText("CALCULADO:");
        jLabelTotalVentas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTotalReal.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabelTotalReal.setText("CONTADO:");
        jLabelTotalReal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelDiferencia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabelDiferencia.setText("DIFERENCIA:");
        jLabelDiferencia.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTextFieldDiferencia.setEditable(false);
        jTextFieldDiferencia.setBackground(new java.awt.Color(245, 150, 110));
        jTextFieldDiferencia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabelRetiro.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabelRetiro.setText("RETIRO:");
        jLabelRetiro.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabelTotalCaja.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabelTotalCaja.setText("TOTAL EN CAJA:");
        jLabelTotalCaja.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jTextFieldTotalCaja.setEditable(false);
        jTextFieldTotalCaja.setBackground(new java.awt.Color(245, 150, 110));
        jTextFieldTotalCaja.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jLabel1.setBackground(java.awt.Color.lightGray);
        jLabel1.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CORTE DE CAJA");
        jLabel1.setOpaque(true);

        jSpinnerContado.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jSpinnerContado.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpinnerContado.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerContadoStateChanged(evt);
            }
        });

        jSpinnerRetiro.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jSpinnerRetiro.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));
        jSpinnerRetiro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerRetiroStateChanged(evt);
            }
        });

        jSpinnerFechaCorte.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jSpinnerFechaCorte.setModel(new javax.swing.SpinnerDateModel());

        jLabelFechaCorte.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabelFechaCorte.setText("FECHA CORTE:");

        jButtonCaluclarContado.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jButtonCaluclarContado.setText("Ʃ");
        jButtonCaluclarContado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaluclarContadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelRetiro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTotalReal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinnerRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabelFechaCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonCaluclarContado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinnerContado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldTotalVentas)
                                    .addComponent(jLabelTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldDiferencia)
                                    .addComponent(jLabelDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldTotalCaja)
                                .addComponent(jLabelTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSpinnerFechaCorte, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelFechaCorte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerFechaCorte, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldDiferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTotalReal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinnerContado, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(jButtonCaluclarContado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTotalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        this.setTransaccionCancelada(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jSpinnerContadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerContadoStateChanged
        
        this.contado = (double) this.jSpinnerContado.getValue();
        setDiferencia( getContado() - getCalculado() );
        setTotalCaja( getContado() - getRetiroCaja() );
    }//GEN-LAST:event_jSpinnerContadoStateChanged

    private void jSpinnerRetiroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerRetiroStateChanged
        
        this.retiroCaja = (double) this.jSpinnerRetiro.getValue();
        setTotalCaja( getContado() - getRetiroCaja() );
    }//GEN-LAST:event_jSpinnerRetiroStateChanged

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed

        String mensaje = "Va a realizar un corte de caja. Si confirma, "
                + "las ventas seleccionadas quedaran asociadas a este corte "
                + "\n¿Desea continuar?";
        String titulo = "¿Desea continuar?";
        
        int confirmacion = JOptionPane.showConfirmDialog(this, mensaje, titulo, JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if ( confirmacion == JOptionPane.YES_OPTION ){ 
          
            this.contado = (double) this.jSpinnerContado.getValue();
            this.retiroCaja = (double) this.jSpinnerRetiro.getValue();
            setDiferencia( getContado() - getCalculado() );
            setTotalCaja( getContado() - getRetiroCaja() );
            setFechaCorte((Date) this.jSpinnerFechaCorte.getValue());
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
            this.setTransaccionCancelada(false);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        this.setTransaccionCancelada(true);
    }//GEN-LAST:event_formWindowClosing

    private void jButtonCaluclarContadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaluclarContadoActionPerformed
        
        JDialogCalculadoraCaja calucaldora = new JDialogCalculadoraCaja(null, true);
        calucaldora.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        calucaldora.setLocationRelativeTo(this);
        calucaldora.setVisible(true);
        
        if ( !calucaldora.isCancelado() ){
            
            setContado(calucaldora.getTotal());
        }
        
    }//GEN-LAST:event_jButtonCaluclarContadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCorteCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrameCorteCaja dialog = new JFrameCorteCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCaluclarContado;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDiferencia;
    private javax.swing.JLabel jLabelFechaCorte;
    private javax.swing.JLabel jLabelRetiro;
    private javax.swing.JLabel jLabelTotalCaja;
    private javax.swing.JLabel jLabelTotalReal;
    private javax.swing.JLabel jLabelTotalVentas;
    private javax.swing.JSpinner jSpinnerContado;
    private javax.swing.JSpinner jSpinnerFechaCorte;
    private javax.swing.JSpinner jSpinnerRetiro;
    private javax.swing.JTextField jTextFieldDiferencia;
    private javax.swing.JTextField jTextFieldTotalCaja;
    private javax.swing.JTextField jTextFieldTotalVentas;
    // End of variables declaration//GEN-END:variables

    // Custom variables
    private double contado;
    private double calculado;
    private double diferencia;
    private double retiroCaja;
    private double totalCaja;  
    private boolean transaccionCancelada;
    private Date fechaCorte;
}
